### ISSUE TITLE
compare with msckf

### ISSUE THREAD

**Issue by wolf943134497** [Horizon1026/ESKF_Estimator#1]
@Horizon1026  Thanks for your great works!

Compared with msckf vio, the advantages of eskf vio？
Have you compared the accuracy and speed of these two algorithms?

thanks!

**Comment by Horizon1026** [comment]
Thank you! This repo is only for personal learning. Accuracy and speed have not been compared for lake of time. Annotation is available in the code. I hope this can help you!



---- Replied Message ----
| From | ***@***.***> |
| Date | 12/13/2022 11:30 |
| To | ***@***.***> |
| Cc | JiaPeng ***@***.***>***@***.***> |
| Subject | [Horizon1026/ESKF_Estimator] compare with msckf (Issue #1) |

@Horizon1026 Thanks for your great works!

Compared with msckf vio, the advantages of eskf vio？
Have you compared the accuracy and speed of these two algorithms?

thanks!
